### ISSUE TITLE
_ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by JanBoos** [costastf/toonapilib#18]
Running a small program (Toon_1.0.py for extracting room temperature) with toonapilib.py on my Synology with python 2.7 I got the following ctitical error:

**/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Traceback (most recent call last):
  File "/volume1/homes/Jan/Pythonscripts/Toon/Toon_1.0.py", line 8, in <module>
    from toonapilib import Toon
  File "/volume1/homes/Jan/Pythonscripts/Toon/toonapilib.py", line 40, in <module>
    from .configuration import STATES, STATE_CACHING_SECONDS, BURNER_STATES
_ValueError: Attempted relative import in non-package**_

Strange thing is than on my windows PC Toon_1.0.py is running flawless.

PS: I found probably 1 error in toonapilib.py. I think that the conversion of toon.temperature has to be (i got only temperatures 19, 20, 21 instead of 19, 19.5, 20, 20.5, 21):
float (toon.temperature) / 100
in stead of:
float (toon.temperature / 100)

**Comment by JanBoos** [comment]
There was a second toonapilib.py in the user directory. I found that was the problem
