### ISSUE TITLE
InvalidConsumerSecret

### ISSUE THREAD

**Issue by JKorf** [costastf/toonapilib#36]
Hi Costas,
I've been getting some (seemingly) random InvalidConsumerSecret - invalid request errors. Most of the time the calls work fine, but sometimes I get the following error:
````
Time: 2019-06-02 15-30-35 
Error: InvalidConsumerSecret 
Info: Error in API request 
Call stack: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app 
response = self.full_dispatch_request() 
File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request 
rv = self.handle_user_exception(e) 
File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function 
return cors_after_request(app.make_response(f(*args, **kwargs))) 
File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception 
reraise(exc_type, exc_value, tb) 
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise 
raise value 
File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request 
rv = self.dispatch_request() 
File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request 
return self.view_functions[rule.endpoint](**req.view_args) 
File "/home/pi/Scripts/Webserver/Controllers/ToonController.py", line 14, in get_toon_status 
status = ToonManager().get_status() 
File "/home/pi/Scripts/Controllers/ToonManager.py", line 15, in get_status 
return self.api.thermostat_info 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 398, in thermostat_info 
info = self._get_status_value('thermostatInfo') 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 352, in _get_status_value 
output = self.status[value] 
File "/usr/local/lib/python3.5/dist-packages/cachetools/__init__.py", line 46, in wrapper 
v = func(*args, **kwargs) 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 239, in status 
response = requests.get(url, headers=self._headers) 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 258, in _patched_request 
response = self.original_request(*args, **kwargs) 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 258, in _patched_request 
response = self.original_request(*args, **kwargs) 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 272, in _patched_request 
self._token = self._refresh_token() 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 214, in _refresh_token 
return self._retrieve_token(payload) 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 225, in _retrieve_token 
raise InvalidConsumerSecret(response.text) 
toonapilib.toonapilibexceptions.InvalidConsumerSecret: {"fault":{"faultstring":"invalid_request","detail":{"errorcode":"invalid_request"}}}
````

Any idea?

**Comment by JKorf** [comment]
Sometimes it returns a different error:
`toonapilib.toonapilibexceptions.InvalidConsumerSecret: {"fault":{"faultstring":"Invalid Refresh Token","detail":{"errorcode":"keymanagement.service.invalid_refresh_token"}}}`

And I also get this one sometimes, might be related:
````
Time: 2019-06-06 07-35-02 
Error: JSONDecodeError 
Info: Rule error 
Call stack: 
Traceback (most recent call last): 
File "/home/pi/Scripts/Controllers/RuleManager.py", line 325, in check_rules 
rule.execute() 
File "/home/pi/Scripts/Controllers/RuleManager.py", line 47, in execute 
action.execute() 
File "/home/pi/Scripts/Controllers/RuleManager.py", line 225, in execute 
ToonManager().set_temperature(self.temp) 
File "/home/pi/Scripts/Controllers/ToonManager.py", line 23, in set_temperature 
self.api.thermostat = temp 
File "/usr/local/lib/python3.5/dist-packages/toonapilib/toonapilib.py", line 518, in thermostat 
data = response.json() 
File "/usr/lib/python3/dist-packages/requests/models.py", line 850, in json 
return complexjson.loads(self.text, **kwargs) 
File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads 
return _default_decoder.decode(s) 
File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 374, in decode 
obj, end = self.raw_decode(s) 
File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 404, in raw_decode 
return self.scan_once(s, idx=_w(s, idx).end()) 
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````

**Comment by costastf** [comment]
Hi @JKorf , this seems very much like an inconsistent server response. The exception thrown is a bit generic and misleading as I could not know all the possible errors the could be returned (although it seems you got them all  😃 ) but it still seems like it is a server side thing. Not really sure how I could help here, except making the exception a bit more specific, although that would not solve your problem.

**Comment by costastf** [comment]
Especially the last one seems like it is not a valid json, which could be a load balancer text error response. I know that quby are on aws and have seen load balancing errors before. The only thing I could suggest is to try to extend the caching period for a while and see if that helps.

**Comment by JKorf** [comment]
Figured there wouldn't be a lot you could do, but maybe you had seen it before. I'll have a look and maybe contact the toon api devs to see what's going on. 

Thanks again for the api though, I've been successfully using it for a couple of months to adjust the temperature when leaving/arriving home :)

**Comment by costastf** [comment]
That's lovely to hear, thanks! If you contact them and need to make the errors clearer please don't hesitate to reopen this issue.

**Comment by JKorf** [comment]
As a follow up, I haven't been able to get in contact with the devs, emails result in no response so that's kinda sad. Anyway, I think a issue might be I'm sending 2 requests simultaneously, retrieving gas and power statistics. Most times the seconds requests fails, but succeeds on a retry. Not sure what the problem is, but for me a retry for the request does the job.
