### ISSUE TITLE
error when combining this with Home Assistant

### ISSUE THREAD

**Issue by scheric** [costastf/toonapilib#8]
I am using  https://github.com/krocat/ToonHA

I can receive data from my Toon reliably. but toonapilib is intersecting with all of the automatic discovery of devices that Home Assistant has. (like: Chromecast, Plex, ....)

it gives this error:
```Thu Apr 26 2018 17:21:34 GMT+0200 (West-Europa (zomertijd))

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 145, in scan_devices
    results = await hass.async_add_job(_discover, netdisco)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 173, in _discover
    for disc in netdisco.discover():
  File "/usr/lib/python3.6/site-packages/netdisco/discovery.py", line 92, in discover
    return [dis for dis, checker in self.discoverables.items()
  File "/usr/lib/python3.6/site-packages/netdisco/discovery.py", line 93, in <listcomp>
    if checker.is_discovered()]
  File "/usr/lib/python3.6/site-packages/netdisco/discoverables/__init__.py", line 17, in is_discovered
    return len(self.get_entries()) > 0
  File "/usr/lib/python3.6/site-packages/netdisco/discoverables/huawei_router.py", line 12, in get_entries
    "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1"
  File "/usr/lib/python3.6/site-packages/netdisco/discoverables/__init__.py", line 73, in find_by_device_description
    return self.netdis.ssdp.find_by_device_description(values)
  File "/usr/lib/python3.6/site-packages/netdisco/ssdp.py", line 74, in find_by_device_description
    if location not in seen and entry.match_device_description(values):
  File "/usr/lib/python3.6/site-packages/netdisco/ssdp.py", line 172, in match_device_description
    device = self.description.get('device')
  File "/usr/lib/python3.6/site-packages/netdisco/ssdp.py", line 143, in description
    xml = requests.get(url, timeout=5).text
  File "/config/deps/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 247, in _patched_request
    if response.status_code == 401 and response.json().get('fault', {}).get(
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I do not get this error when i remove toonapilib

> What i tried to get it working:
(This is not a working solution)
deleting this: in \config\deps\lib\python3.6\site-packages\toonapilib\toonapilib.py
```
        if response.status_code == 401 and response.json().get('fault', {}).get(
                'faultstring', '') == 'Access Token expired':
            self._logger.info('Expired token detected, trying to refresh!')
            self._token = self._refresh_token()
            self._set_headers(self._token)
            kwargs['headers'].update(
                {'Authorization': 'Bearer {}'.format(self._token.access_token)})
            self._logger.debug('Updated headers, trying again initial request')
            response = self.original_request(url, **kwargs)
```

What could be a working solution so i can use this toonapilib and Chromecast discovery?

> Workaround to get Chromecast working again with toonapilib
add this: to your configuration.yaml in Home Assistant. (This only solves the problem with Cromecast and not other devices)
```
media_player:
  - platform: cast
```

**Comment by scheric** [comment]
I solved the problem. 
does anyone think this is not a suitable option?
This:
```
        if response.status_code == 401 and response.json().get('fault', {}).get(
```
to:
```
        if response.status_code == 402 and response.json().get('fault', {}).get(
```

**Comment by frenck** [comment]
@scheric Yep! Solves it for me too 👍

**Comment by costastf** [comment]
Could you please try the code in https://github.com/costastf/toonapilib/tree/f-HA-detection-fix and give me feedback on that? @frenck as I mentioned on the pull request I closed this change does not fix anything. it just breaks the automatic reauthentication when the toon token expires. After an hour you will lose connectivity. Please try out the branch I mention and give feedback on this thread. Thanks!

**Comment by scheric** [comment]
@costastf 
It sort-off works. I am getting data from my toon without any errors. And i have compatibilety with cromecast (without a workaround) but sometimes after a reboot  reboot i get this error
![knipsedsl](https://user-images.githubusercontent.com/38077357/39410480-17eb93ee-4bf9-11e8-891a-f59162fa0c71.PNG)
With another (more useful for debugging) error that i did not capture 

I am quite convinced that it works because i cant get the error anymore after a reboot. I will check within a few days if there are any problems with compatibility.

thanks for fixing :clap:

**Comment by costastf** [comment]
I guess that that is normal since when something has not responded with a state yet when HA is querying it, the state is set to unknown, so that is probably just a timing issue. If you get something more descriptive as output please paste it here so we can follow up on it.

**Comment by scheric** [comment]
@costastf 
I am confined it works. I am not getting any errors after a reboot or after a long period of time.
And again thanks for fixing 👏
